using System.Collections.Generic;
using System.Linq;
using OpenNefia.XamlNameGenerator.Domain;
using XamlX.TypeSystem;

namespace OpenNefia.XamlNameGenerator.Generator;

internal class InitializeComponentCodeGenerator : ICodeGenerator
{
    private readonly bool _diagnosticsAreConnected;
    private const string AttachDevToolsCodeBlock = @"
#if DEBUG
            if (attachDevTools)
            {
                this.AttachDevTools();
            }
#endif
";
    private const string AttachDevToolsParameterDocumentation
        = @"        /// <param name=""attachDevTools"">Should the dev tools be attached.</param>
";

    public InitializeComponentCodeGenerator(IXamlTypeSystem types)
    {
        _diagnosticsAreConnected = false; // types.FindAssembly("Avalonia.Diagnostics") != null;
    }

    public string GenerateCode(string className, IList<string> generics, string nameSpace, IXamlType xamlType, IEnumerable<ResolvedName> names)
    {
        var properties = new List<string>();
        var initializations = new List<string>();
        foreach (var (typeName, name, fieldModifier) in names)
        {
            properties.Add($"        {fieldModifier} global::{typeName} {name};");
            initializations.Add($"            {name} = this.FindControl<global::{typeName}>(\"{name}\");");
        }
        var genericsStr = string.Empty;
        if (generics.Count > 0)
            genericsStr = $"<{string.Join(", ", generics)}>";

        var attachDevTools = _diagnosticsAreConnected && IsWindow(xamlType);

        return $@"// <auto-generated />

using OpenNefia.Core.UI.Wisp;
using OpenNefia.Core.UI.Wisp.Controls;

namespace {nameSpace}
{{
    partial class {className}{genericsStr}
    {{
{string.Join("\n", properties)}

        /// <summary>
        /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if OpenNefia.Diagnostics package is referenced).
        /// </summary>
        /// <param name=""loadXaml"">Should the XAML be loaded into the component.</param>
{(attachDevTools ? AttachDevToolsParameterDocumentation : string.Empty)}
        public void InitializeComponent(bool loadXaml = true{(attachDevTools ? ", bool attachDevTools = true" : string.Empty)})
        {{
            if (loadXaml)
            {{
                OpenNefiaXamlLoader.Load(this);
            }}
{(attachDevTools ? AttachDevToolsCodeBlock : string.Empty)}
{string.Join("\n", initializations)}
        }}
    }}
}}
";
    }

    private static bool IsWindow(IXamlType xamlType)
    {
        var type = xamlType;
        bool isWindow;
        do
        {
            isWindow = type.FullName == "OpenNefia.Core.UI.Wisp.CustomControls.DefaultWindow";
            type = type.BaseType;
        } while (!isWindow && type != null);

        return isWindow;
    }
}