- type: Elona.Action
  id: Elona.HarvestMana
  hspIds:
    elona122: 621
  skillID: Elona.ActionHarvestMana
  effectID: Elona.ActionHarvestMana
  staminaCost: 10
  difficulty: 700
  maxRange: 0
- type: Elona.Skill
  id: Elona.ActionHarvestMana
  hspIds:
    elona122: 621
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionHarvestMana
  hspIds:
    elona122: 621
  parent: BaseEffect
  components:
  - type: EffectTargetSelfOrNearby
  - type: EffectBaseDamageDice
    finalDamage: power / 2 + randInt(power / 2 + 1)
  - type: EffectDamageHealMP

- type: Elona.Action
  id: Elona.AbsorbMagic
  hspIds:
    elona122: 624
  skillID: Elona.ActionAbsorbMagic
  effectID: Elona.ActionAbsorbMagic
  staminaCost: 25
- type: Elona.Skill
  id: Elona.ActionAbsorbMagic
  hspIds:
    elona122: 624
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionAbsorbMagic
  hspIds:
    elona122: 624
  parent: BaseEffect
  components:
  - type: EffectTargetSelf
  - type: EffectBaseDamageDice
    extraVariables:
      piety: !type:PietyFormulaVariable {}
    diceX: 1 + skillLevel / 20
    diceY: piety / 140 + 1 + 1
    bonus: 0
  - type: EffectDamageHealMP
    messageKey: Elona.Effect.HealMP.AbsorbMagic

- type: Elona.Action
  id: Elona.Mirror
  hspIds:
    elona122: 626
  skillID: Elona.ActionMirror
  effectID: Elona.ActionMirror
  staminaCost: 30
  difficulty: 500
- type: Elona.Skill
  id: Elona.ActionMirror
  hspIds:
    elona122: 626
  skillType: Action
  relatedSkill: Elona.AttrPerception
- type: Entity
  id: Elona.ActionMirror
  hspIds:
    elona122: 626
  parent: BaseEffect
  components:
  - type: EffectTargetSelf
  - type: EffectMirror

- type: Elona.Action
  id: Elona.Change
  hspIds:
    elona122: 628
  skillID: Elona.ActionChange
  effectID: Elona.ActionChange
  staminaCost: 10
  maxRange: 6
- type: Elona.Skill
  id: Elona.ActionChange
  hspIds:
    elona122: 628
  skillType: Action
  relatedSkill: Elona.AttrPerception
- type: Entity
  id: Elona.ActionChange
  hspIds:
    elona122: 628
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectBaseDamageDice
    # Minimum creature level for success
    finalPower: power / 10 + 10
  - type: EffectTargetOther
  - type: EffectChange

- type: Elona.Action
  id: Elona.DrawCharge
  hspIds:
    elona122: 629
  skillID: Elona.ActionDrawCharge
  effectID: Elona.ActionDrawCharge
  staminaCost: 1
- type: Elona.Skill
  id: Elona.ActionDrawCharge
  hspIds:
    elona122: 629
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionDrawCharge
  hspIds:
    elona122: 629
  parent: BaseEffect
  components:
  - type: EffectTargetSelf
  - type: EffectDrawCharge

- type: Elona.Action
  id: Elona.FillCharge
  hspIds:
    elona122: 630
  skillID: Elona.ActionFillCharge
  effectID: Elona.ActionFillCharge
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionFillCharge
  hspIds:
    elona122: 630
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionFillCharge
  hspIds:
    elona122: 630
  parent: BaseEffect
  components:
  - type: EffectTargetSelf
  - type: EffectBaseDamageDice
    # If 0, recharge fails
    finalDamage: randInt(power / 25 + 1)
  - type: EffectRecharge
    rechargePowerCost: 10
    # >>>>>>>> elona122/shade2/proc.hsp:3131 			p=1+rnd(iChargeLevel/2+1) : if p+iCharge(ci)>iC ...
    addedCharges: 1 + randInt(maxCharges / 2 + 1)
    # <<<<<<<< elona122/shade2/proc.hsp:3131 			p=1+rnd(iChargeLevel/2+1) : if p+iCharge(ci)>iC ..

- type: Elona.Action
  id: Elona.Swarm
  hspIds:
    elona122: 631
  skillID: Elona.ActionSwarm
  effectID: Elona.ActionSwarm
  staminaCost: 5
  difficulty: 220
- type: Elona.Skill
  id: Elona.ActionSwarm
  hspIds:
    elona122: 631
  skillType: Action
  relatedSkill: Elona.AttrStrength
- type: Entity
  id: Elona.ActionSwarm
  hspIds:
    elona122: 631
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetSelf
  - type: EffectAreaBall
  - type: EffectDamageRelations
    validRelations: Enemy~Neutral
  - type: EffectDamageMessage
    rootKey: Elona.Effect.Swarm.Apply
    color: '#afafff'
  - type: EffectMeleeAttack

- type: Elona.Action
  id: Elona.EyeOfMutation
  hspIds:
    elona122: 632
  skillID: Elona.ActionEyeOfMutation
  effectID: Elona.ActionEyeOfMutation
  staminaCost: 10
  maxRange: 2
- type: Elona.Skill
  id: Elona.ActionEyeOfMutation
  hspIds:
    elona122: 632
  skillType: Action
  relatedSkill: Elona.AttrWill
- type: Entity
  id: Elona.ActionEyeOfMutation
  hspIds:
    elona122: 632
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectBaseDamageDice
    # Number of mutations
    finalDamage: 1
  - type: EffectDamageCastInstead
    ifTarget: NotPlayer
    effectID: Elona.ActionChange
  - type: EffectDamageSuccessRate
    messageKey: Elona.Effect.Mutation.Eye
    successRate: 2 / 3
  - type: EffectMutation
    mutationTimes: 1

- type: Elona.Action
  id: Elona.EyeOfEther
  hspIds:
    elona122: 633
  skillID: Elona.ActionEyeOfEther
  effectID: Elona.ActionEyeOfEther
  staminaCost: 10
  maxRange: 2
- type: Elona.Skill
  id: Elona.ActionEyeOfEther
  hspIds:
    elona122: 633
  skillType: Action
  relatedSkill: Elona.AttrWill
- type: Entity
  id: Elona.ActionEyeOfEther
  hspIds:
    elona122: 633
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectEyeOfEther
    addedCorruption: 100

- type: Elona.Action
  id: Elona.SuspiciousHand
  hspIds:
    elona122: 635
  skillID: Elona.ActionSuspiciousHand
  effectID: Elona.ActionSuspiciousHand
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionSuspiciousHand
  hspIds:
    elona122: 635
  skillType: Action
  relatedSkill: Elona.AttrDexterity
- type: Entity
  id: Elona.ActionSuspiciousHand
  hspIds:
    elona122: 635
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetDirection
  - type: EffectBaseDamageDice
    extraVariables:
      gold: !type:CurrencyFormulaVariable
        type: Gold
    finalDamage: randInt(gold / 10 + 1)
  - type: EffectDamageTeleport
    subject: Source
    position: !type:WholeMapTeleportPosition {}
    messageKey: Elona.Effect.SuspiciousHand.Escapes
  - type: EffectSuspiciousHand

- type: Elona.Action
  id: Elona.EyeOfInsanity
  hspIds:
    elona122: 636
  skillID: Elona.ActionEyeOfInsanity
  effectID: Elona.ActionEyeOfInsanity
  staminaCost: 10
  maxRange: 2
- type: Elona.Skill
  id: Elona.ActionEyeOfInsanity
  hspIds:
    elona122: 636
  skillType: Action
  relatedSkill: Elona.AttrCharisma
- type: Entity
  id: Elona.ActionEyeOfInsanity
  hspIds:
    elona122: 636
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectAreaMessage
    messageKey: Elona.Effect.EyeOfInsanity.Message
    color: '#b99bd7'
  - type: EffectDamageSanity

- type: Elona.Action
  id: Elona.EyeOfDimness
  hspIds:
    elona122: 638
  skillID: Elona.ActionEyeOfDimness
  effectID: Elona.ActionEyeOfDimness
  staminaCost: 10
  maxRange: 2
- type: Elona.Skill
  id: Elona.ActionEyeOfDimness
  hspIds:
    elona122: 638
  skillType: Action
  relatedSkill: Elona.AttrCharisma
- type: Entity
  id: Elona.ActionEyeOfDimness
  hspIds:
    elona122: 638
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectDamageStatusEffects
    # >>>>>>>> elona122/shade2/proc.hsp:3399 	dmgCon tc,conDim,200 ...
    statusEffects:
    - id: Elona.Dimming
      power: 200
    # <<<<<<<< elona122/shade2/proc.hsp:3399 	dmgCon tc,conDim,200 ..

- type: Elona.Action
  id: Elona.Curse
  hspIds:
    elona122: 645
  skillID: Elona.ActionCurse
  effectID: Elona.ActionCurse
  staminaCost: 10
  maxRange: 4
  difficulty: 100
- type: Elona.Skill
  id: Elona.ActionCurse
  hspIds:
    elona122: 645
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionCurse
  hspIds:
    elona122: 645
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectAreaMessage
    messageKey: Elona.Effect.Curse.Action
  - type: EffectBaseDamageDice
    # Curse power, compared against LUK and enchant strength
    finalDamage: power / 2
  - type: EffectCurse

- type: Elona.Action
  id: Elona.Insult
  hspIds:
    elona122: 648
  skillID: Elona.ActionInsult
  effectID: Elona.ActionInsult
  staminaCost: 10
  maxRange: 4
- type: Elona.Skill
  id: Elona.ActionInsult
  hspIds:
    elona122: 648
  skillType: Action
  relatedSkill: Elona.AttrCharisma
- type: Entity
  id: Elona.ActionInsult
  hspIds:
    elona122: 648
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectInsult # Just outputs some special dialog
  - type: EffectDamageStatusEffects
    statusEffects:
    # >>>>>>>> elona122/shade2/proc.hsp:3399 	dmgCon tc,conDim,200 ...
    - id: Elona.Dimming
      power: 200
    # <<<<<<<< elona122/shade2/proc.hsp:3399 	dmgCon tc,conDim,200 ..

- type: Elona.Action
  id: Elona.DistantAttack4
  hspIds:
    elona122: 649
  skillID: Elona.ActionDistantAttack4
  effectID: Elona.ActionDistantAttack
  staminaCost: 10
  maxRange: 4
- type: Elona.Skill
  id: Elona.ActionDistantAttack4
  hspIds:
    elona122: 649
  skillType: Action
  relatedSkill: Elona.AttrStrength
- type: Elona.Action
  id: Elona.DistantAttack7
  hspIds:
    elona122: 650
  skillID: Elona.ActionDistantAttack7
  effectID: Elona.ActionDistantAttack
  staminaCost: 10
  maxRange: 7
- type: Elona.Skill
  id: Elona.ActionDistantAttack7
  hspIds:
    elona122: 650
  skillType: Action
  relatedSkill: Elona.AttrStrength
- type: Entity
  id: Elona.ActionDistantAttack
  hspIds:
    elona122: 649
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectDistantAttack

- type: Elona.Action
  id: Elona.Scavenge
  hspIds:
    elona122: 651
  skillID: Elona.ActionScavenge
  effectID: Elona.ActionScavenge
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionScavenge
  hspIds:
    elona122: 651
  skillType: Action
  relatedSkill: Elona.AttrDexterity
- type: Entity
  id: Elona.ActionScavenge
  hspIds:
    elona122: 651
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetDirection
  - type: EffectScavenge

- type: Elona.Action
  id: Elona.EyeOfMana
  hspIds:
    elona122: 652
  skillID: Elona.ActionEyeOfMana
  effectID: Elona.ActionEyeOfMana
  staminaCost: 10
  maxRange: 2
- type: Elona.Skill
  id: Elona.ActionEyeOfMana
  hspIds:
    elona122: 652
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionEyeOfMana
  hspIds:
    elona122: 652
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectBaseDamageDice
    finalDamage: randInt(20) + 1
  - type: EffectDamageMP

- type: Elona.Action
  id: Elona.Vanish
  hspIds:
    elona122: 653
  skillID: Elona.ActionVanish
  effectID: Elona.ActionVanish
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionVanish
  hspIds:
    elona122: 653
  skillType: Action
  relatedSkill: Elona.AttrPerception
- type: Entity
  id: Elona.ActionVanish
  hspIds:
    elona122: 653
  parent: BaseEffect
  components:
  - type: Effect
  - type: EffectTargetSelf
  - type: EffectVanish

- type: Elona.Action
  id: Elona.Impregnate
  hspIds:
    elona122: 654
  skillID: Elona.ActionImpregnate
  effectID: Elona.ActionImpregnate
  staminaCost: 15
  maxRange: 1
- type: Elona.Skill
  id: Elona.ActionImpregnate
  hspIds:
    elona122: 654
  skillType: Action
  relatedSkill: Elona.AttrPerception
- type: Entity
  id: Elona.ActionImpregnate
  hspIds:
    elona122: 654
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectImpregnate

- type: Elona.Action
  id: Elona.Cheer
  hspIds:
    elona122: 656
  skillID: Elona.ActionCheer
  effectID: Elona.ActionCheer
  staminaCost: 28
  maxRange: 6
  difficulty: 500
- type: Elona.Skill
  id: Elona.ActionCheer
  hspIds:
    elona122: 656
  skillType: Action
  relatedSkill: Elona.AttrCharisma
- type: Entity
  id: Elona.ActionCheer
  hspIds:
    elona122: 656
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetSelfOrNearby
  - type: EffectAreaMessage
    messageKey: Elona.Effect.Cheer.Cheers
  - type: EffectAreaBall
  # >>>>>>>> elona122/shade2/proc.hsp:3352 	if cc<maxFollower:if cnt>=maxFollower:continue:el ...
  - type: EffectDamageRelations
    validRelations: Ally~Ally
  # <<<<<<<< elona122/shade2/proc.hsp:3352 	if cc<maxFollower:if cnt>=maxFollower:continue:el ..
  - type: EffectDamageMessage
    rootKey: Elona.Effect.Cheer.IsExcited
    color: '#afafff'
  - type: EffectCheer

- type: Elona.Action
  id: Elona.Mewmewmew
  hspIds:
    elona122: 657
  skillID: Elona.ActionMewmewmew
  effectID: Elona.ActionMewmewmew
  staminaCost: 1
  difficulty: 500
- type: Elona.Skill
  id: Elona.ActionMewmewmew
  hspIds:
    elona122: 657
  skillType: Action
  relatedSkill: Elona.AttrLuck
- type: Entity
  id: Elona.ActionMewmewmew
  hspIds:
    elona122: 657
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetSelfOrNearby
  # - type: EffectAreaWholeMap
  - type: EffectMewMewMew

- type: Elona.Action
  id: Elona.Decapitation
  hspIds:
    elona122: 658
  skillID: Elona.ActionDecapitation
  effectID: Elona.ActionDecapitation
  staminaCost: 10
  maxRange: 1
- type: Elona.Skill
  id: Elona.ActionDecapitation
  hspIds:
    elona122: 658
  skillType: Action
  relatedSkill: Elona.AttrDexterity
- type: Entity
  id: Elona.ActionDecapitation
  hspIds:
    elona122: 658
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectDecapitation

- type: Elona.Action
  id: Elona.DropMine
  hspIds:
    elona122: 659
  skillID: Elona.ActionDropMine
  effectID: Elona.ActionDropMine
  staminaCost: 15
- type: Elona.Skill
  id: Elona.ActionDropMine
  hspIds:
    elona122: 659
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionDropMine
  hspIds:
    elona122: 659
  parent: BaseEffect
- type: Entity
  id: Elona.ActionDropMine
  hspIds:
    elona122: 659
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetSelfOrNearby
  - type: EffectAreaMessage
    messageKey: A
  - type: EffectDamageMObj
    mObjID: Elona.MObjMine
