
- type: Elona.Action
  id: Elona.HarvestMana
  hspIds:
    elona122: 621
#  difficulty: 700
  skillID: Elona.ActionHarvestMana
  effectID: Elona.ActionHarvestMana
  staminaCost: 10
  difficulty: 700
- type: Elona.Skill
  id: Elona.ActionHarvestMana
  hspIds:
    elona122: 621
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionHarvestMana
  hspIds:
    elona122: 621
  parent: BaseEffect

- type: Elona.Action
  id: Elona.PrayerOfJure
  hspIds:
    elona122: 623
  skillID: Elona.ActionPrayerOfJure
  effectID: Elona.ActionPrayerOfJure
  staminaCost: 30
- type: Elona.Skill
  id: Elona.ActionPrayerOfJure
  hspIds:
    elona122: 623
  skillType: Action
  relatedSkill: Elona.AttrWill
- type: Entity
  id: Elona.ActionPrayerOfJure
  hspIds:
    elona122: 623
  parent: BaseEffect

- type: Elona.Action
  id: Elona.AbsorbMagic
  hspIds:
    elona122: 624
  skillID: Elona.ActionAbsorbMagic
  effectID: Elona.ActionAbsorbMagic
  staminaCost: 25
- type: Elona.Skill
  id: Elona.ActionAbsorbMagic
  hspIds:
    elona122: 624
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionAbsorbMagic
  hspIds:
    elona122: 624
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Mirror
  hspIds:
    elona122: 626
#  difficulty: 500
  skillID: Elona.ActionMirror
  effectID: Elona.ActionMirror
  staminaCost: 30
  difficulty: 500
- type: Elona.Skill
  id: Elona.ActionMirror
  hspIds:
    elona122: 626
  skillType: Action
  relatedSkill: Elona.AttrPerception
- type: Entity
  id: Elona.ActionMirror
  hspIds:
    elona122: 626
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Change
  hspIds:
    elona122: 628
  skillID: Elona.ActionChange
  effectID: Elona.ActionChange
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionChange
  hspIds:
    elona122: 628
  skillType: Action
  relatedSkill: Elona.AttrPerception
- type: Entity
  id: Elona.ActionChange
  hspIds:
    elona122: 628
  parent: BaseEffect

- type: Elona.Action
  id: Elona.DrawCharge
  hspIds:
    elona122: 629
  skillID: Elona.ActionDrawCharge
  effectID: Elona.ActionDrawCharge
  staminaCost: 1
- type: Elona.Skill
  id: Elona.ActionDrawCharge
  hspIds:
    elona122: 629
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionDrawCharge
  hspIds:
    elona122: 629
  parent: BaseEffect

- type: Elona.Action
  id: Elona.FillCharge
  hspIds:
    elona122: 630
  skillID: Elona.ActionFillCharge
  effectID: Elona.ActionFillCharge
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionFillCharge
  hspIds:
    elona122: 630
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionFillCharge
  hspIds:
    elona122: 630
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Swarm
  hspIds:
    elona122: 631
#  difficulty: 220
  skillID: Elona.ActionSwarm
  effectID: Elona.ActionSwarm
  staminaCost: 5
  difficulty: 220
- type: Elona.Skill
  id: Elona.ActionSwarm
  hspIds:
    elona122: 631
  skillType: Action
  relatedSkill: Elona.AttrStrength
- type: Entity
  id: Elona.ActionSwarm
  hspIds:
    elona122: 631
  parent: BaseEffect

- type: Elona.Action
  id: Elona.EyeOfMutation
  hspIds:
    elona122: 632
  skillID: Elona.ActionEyeOfMutation
  effectID: Elona.ActionEyeOfMutation
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionEyeOfMutation
  hspIds:
    elona122: 632
  skillType: Action
  relatedSkill: Elona.AttrWill
- type: Entity
  id: Elona.ActionEyeOfMutation
  hspIds:
    elona122: 632
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectBaseDamageDice
    # Number of mutations
    finalDamage: 1
  - type: EffectDamageCastInstead
    ifTarget: NotPlayer
    effectID: Elona.ActionChange
  - type: EffectDamageSuccessRate
    messageKey: Elona.Effect.Mutation.Eye
    successRate: 2 / 3
  - type: EffectMutation
    mutationTimes: 1

- type: Elona.Action
  id: Elona.EyeOfEther
  hspIds:
    elona122: 633
  skillID: Elona.ActionEyeOfEther
  effectID: Elona.ActionEyeOfEther
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionEyeOfEther
  hspIds:
    elona122: 633
  skillType: Action
  relatedSkill: Elona.AttrWill
- type: Entity
  id: Elona.ActionEyeOfEther
  hspIds:
    elona122: 633
  parent: BaseEffect

- type: Elona.Action
  id: Elona.SuspiciousHand
  hspIds:
    elona122: 635
  skillID: Elona.ActionSuspiciousHand
  effectID: Elona.ActionSuspiciousHand
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionSuspiciousHand
  hspIds:
    elona122: 635
  skillType: Action
  relatedSkill: Elona.AttrDexterity
- type: Entity
  id: Elona.ActionSuspiciousHand
  hspIds:
    elona122: 635
  parent: BaseEffect

- type: Elona.Action
  id: Elona.EyeOfInsanity
  hspIds:
    elona122: 636
  skillID: Elona.ActionEyeOfInsanity
  effectID: Elona.ActionEyeOfInsanity
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionEyeOfInsanity
  hspIds:
    elona122: 636
  skillType: Action
  relatedSkill: Elona.AttrCharisma
- type: Entity
  id: Elona.ActionEyeOfInsanity
  hspIds:
    elona122: 636
  parent: BaseEffect

- type: Elona.Action
  id: Elona.EyeOfDimness
  hspIds:
    elona122: 638
  skillID: Elona.ActionEyeOfDimness
  effectID: Elona.ActionEyeOfDimness
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionEyeOfDimness
  hspIds:
    elona122: 638
  skillType: Action
  relatedSkill: Elona.AttrCharisma
- type: Entity
  id: Elona.ActionEyeOfDimness
  hspIds:
    elona122: 638
  parent: BaseEffect

- type: Elona.Action
  id: Elona.SuicideAttack
  hspIds:
    elona122: 644
#  difficulty: 450
  skillID: Elona.ActionSuicideAttack
  effectID: Elona.ActionSuicideAttack
  staminaCost: 20
  difficulty: 450
- type: Elona.Skill
  id: Elona.ActionSuicideAttack
  hspIds:
    elona122: 644
  skillType: Action
  relatedSkill: Elona.AttrConstitution
- type: Entity
  id: Elona.ActionSuicideAttack
  hspIds:
    elona122: 644
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Curse
  hspIds:
    elona122: 645
#  difficulty: 100
  skillID: Elona.ActionCurse
  effectID: Elona.ActionCurse
  staminaCost: 10
  maxRange: 4
  difficulty: 100
- type: Elona.Skill
  id: Elona.ActionCurse
  hspIds:
    elona122: 645
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionCurse
  hspIds:
    elona122: 645
  parent: BaseEffect
  components:
  - type: Effect
    alignment: Negative
  - type: EffectTargetOther
  - type: EffectAreaMessage
    messageKey: Elona.Effect.Curse.Action
  - type: EffectBaseDamageDice
    # Curse power, compared against LUK and enchant strength
    finalDamage: power / 2
  - type: EffectCurse

- type: Elona.Action
  id: Elona.BuffDeathWord
  hspIds:
    elona122: 646
  skillID: Elona.ActionBuffDeathWord
  effectID: Elona.ActionBuffDeathWord
  staminaCost: 15
  difficulty: 500
- type: Elona.Skill
  id: Elona.ActionBuffDeathWord
  hspIds:
    elona122: 646
  skillType: Action
  relatedSkill: Elona.AttrWill
- type: Entity
  id: Elona.ActionBuffDeathWord
  hspIds:
    elona122: 646
  parent: BaseEffect

- type: Elona.Action
  id: Elona.BuffBoost
  hspIds:
    elona122: 647
  skillID: Elona.ActionBuffBoost
  effectID: Elona.ActionBuffBoost
  staminaCost: 50
  difficulty: 500
- type: Elona.Skill
  id: Elona.ActionBuffBoost
  hspIds:
    elona122: 647
  skillType: Action
  relatedSkill: Elona.AttrWill
- type: Entity
  id: Elona.ActionBuffBoost
  hspIds:
    elona122: 647
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Insult
  hspIds:
    elona122: 648
  skillID: Elona.ActionInsult
  effectID: Elona.ActionInsult
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionInsult
  hspIds:
    elona122: 648
  skillType: Action
  relatedSkill: Elona.AttrCharisma
- type: Entity
  id: Elona.ActionInsult
  hspIds:
    elona122: 648
  parent: BaseEffect

- type: Elona.Action
  id: Elona.DistantAttack4
  hspIds:
    elona122: 649
  skillID: Elona.ActionDistantAttack4
  effectID: Elona.ActionDistantAttack4
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionDistantAttack4
  hspIds:
    elona122: 649
  skillType: Action
  relatedSkill: Elona.AttrStrength
- type: Entity
  id: Elona.ActionDistantAttack4
  hspIds:
    elona122: 649
  parent: BaseEffect

- type: Elona.Action
  id: Elona.DistantAttack7
  hspIds:
    elona122: 650
  skillID: Elona.ActionDistantAttack7
  effectID: Elona.ActionDistantAttack7
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionDistantAttack7
  hspIds:
    elona122: 650
  skillType: Action
  relatedSkill: Elona.AttrStrength
- type: Entity
  id: Elona.ActionDistantAttack7
  hspIds:
    elona122: 650
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Scavenge
  hspIds:
    elona122: 651
  skillID: Elona.ActionScavenge
  effectID: Elona.ActionScavenge
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionScavenge
  hspIds:
    elona122: 651
  skillType: Action
  relatedSkill: Elona.AttrDexterity
- type: Entity
  id: Elona.ActionScavenge
  hspIds:
    elona122: 651
  parent: BaseEffect

- type: Elona.Action
  id: Elona.EyeOfMana
  hspIds:
    elona122: 652
  skillID: Elona.ActionEyeOfMana
  effectID: Elona.ActionEyeOfMana
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionEyeOfMana
  hspIds:
    elona122: 652
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionEyeOfMana
  hspIds:
    elona122: 652
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Vanish
  hspIds:
    elona122: 653
  skillID: Elona.ActionVanish
  effectID: Elona.ActionVanish
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionVanish
  hspIds:
    elona122: 653
  skillType: Action
  relatedSkill: Elona.AttrPerception
- type: Entity
  id: Elona.ActionVanish
  hspIds:
    elona122: 653
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Pregnant
  hspIds:
    elona122: 654
  skillID: Elona.ActionPregnant
  effectID: Elona.ActionPregnant
  staminaCost: 15
- type: Elona.Skill
  id: Elona.ActionPregnant
  hspIds:
    elona122: 654
  skillType: Action
  relatedSkill: Elona.AttrPerception
- type: Entity
  id: Elona.ActionPregnant
  hspIds:
    elona122: 654
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Cheer
  hspIds:
    elona122: 656
#  difficulty: 500
  skillID: Elona.ActionCheer
  effectID: Elona.ActionCheer
  staminaCost: 28
  difficulty: 500
- type: Elona.Skill
  id: Elona.ActionCheer
  hspIds:
    elona122: 656
  skillType: Action
  relatedSkill: Elona.AttrCharisma
- type: Entity
  id: Elona.ActionCheer
  hspIds:
    elona122: 656
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Mewmewmew
  hspIds:
    elona122: 657
#  difficulty: 500
  skillID: Elona.ActionMewmewmew
  effectID: Elona.ActionMewmewmew
  staminaCost: 1
  difficulty: 500
- type: Elona.Skill
  id: Elona.ActionMewmewmew
  hspIds:
    elona122: 657
  skillType: Action
  relatedSkill: Elona.AttrLuck
- type: Entity
  id: Elona.ActionMewmewmew
  hspIds:
    elona122: 657
  parent: BaseEffect

- type: Elona.Action
  id: Elona.Decapitation
  hspIds:
    elona122: 658
  skillID: Elona.ActionDecapitation
  effectID: Elona.ActionDecapitation
  staminaCost: 10
- type: Elona.Skill
  id: Elona.ActionDecapitation
  hspIds:
    elona122: 658
  skillType: Action
  relatedSkill: Elona.AttrDexterity
- type: Entity
  id: Elona.ActionDecapitation
  hspIds:
    elona122: 658
  parent: BaseEffect

- type: Elona.Action
  id: Elona.DropMine
  hspIds:
    elona122: 659
  skillID: Elona.ActionDropMine
  effectID: Elona.ActionDropMine
  staminaCost: 15
- type: Elona.Skill
  id: Elona.ActionDropMine
  hspIds:
    elona122: 659
  skillType: Action
  relatedSkill: Elona.AttrMagic
- type: Entity
  id: Elona.ActionDropMine
  hspIds:
    elona122: 659
  parent: BaseEffect
