- type: Entity
  id: Elona.BaseSpellEffect
  abstract: true
  parent: BaseEffect
  components:
  - type: EffectTypeSpell

- type: Entity
  id: Elona.BaseActionEffect
  abstract: true
  parent: BaseEffect
  components:
  - type: EffectTypeAction
