- type: Entity
  id: BaseObject
  abstract: true
  components:
  - type: Chip
    id: Default
  - type: Tag

- type: Entity
  id: BaseChara
  parent: BaseObject
  abstract: true
  hspEntityType: chara
  components:
  - type: Spatial
    isSolid: true
    isOpaque: false
  - type: Chip
    drawDepth: Characters
  - type: TurnOrder
  - type: Moveable
  - type: Level
  - type: Chara
    class: Slime
  - type: Skills
  - type: Faction
  - type: Weight
  - type: Inventory
  - type: VanillaAI

- type: Entity
  id: BaseItem
  parent: BaseObject
  abstract: true
  hspEntityType: item
  components:
  - type: Spatial
    isSolid: false
    isOpaque: false
  - type: Chip
    drawDepth: Items
  - type: Item
  - type: ItemDescription
  - type: Stack
  - type: Weight
  - type: Pickable

- type: Entity
  id: BaseFeat
  parent: BaseObject
  abstract: true
  hspEntityType: feat
  components:
  - type: Spatial
    isSolid: false
    isOpaque: false
  - type: Chip
    drawDepth: Feats

- type: Entity
  id: BaseMef
  parent: BaseObject
  abstract: true
  hspEntityType: mef
  components:
  - type: Chip
    drawDepth: Mefs

- type: Entity
  id: BaseMap
  abstract: true
  components:
  - type: Map
