using OpenNefia.Core.ContentPack;

namespace OpenNefia.Core
{
    internal static class ProgramShared
    {
        internal static void DoMounts(IResourceManagerInternal res)
        {
            res.Initialize("UserData");

            // Assets directory in OpenNefia.Core
            res.MountContentDirectory("../../../../OpenNefia/Assets");

            // Assets directory in OpenNefia.Content
            res.MountContentDirectory("../../../../OpenNefia.Content/Assets");

            // Autogenerated directory holding OpenNefia.Content.dll in build output
            // TODO make this saner
            res.MountContentDirectory("Assets");
        }
    }
}