using OpenNefia.Core.ContentPack;

namespace OpenNefia.Core
{
    internal static class ProgramShared
    {
        internal static void DoMounts(IResourceManagerInternal res)
        {
            res.Initialize("UserData");

#if FULL_RELEASE
            res.MountContentDirectory("Resources/");
#else
            // Assets directory in OpenNefia.Core
            res.MountContentDirectory("../../../../OpenNefia/Resources");

            // Assets directory in OpenNefia.Content
            res.MountContentDirectory("../../../../OpenNefia.Content/Resources");

            // Assets directory held by baked vegetables
            // TODO this is dumb
            res.MountContentDirectory("../../../../OpenNefia.LecchoTorte/Resources");

            // Autogenerated directory holding OpenNefia.Content.dll in build output
            // TODO make this saner
            res.MountContentDirectory("Resources");
#endif
        }
    }
}