using ImGuiNET;
using OpenNefia.Core.Input;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenNefia.Core.DebugView
{
    public sealed partial class DebugViewManager
    {
        private void SetupKeyMap()
        {
            var io = ImGui.GetIO();
            var keyMap = io.KeyMap;

            keyMap[(int)ImGuiKey.Tab] = (int)Keyboard.Key.Tab;
            keyMap[(int)ImGuiKey.LeftArrow] = (int)Keyboard.Key.Left;
            keyMap[(int)ImGuiKey.RightArrow] = (int)Keyboard.Key.Right;
            keyMap[(int)ImGuiKey.UpArrow] = (int)Keyboard.Key.Up;
            keyMap[(int)ImGuiKey.DownArrow] = (int)Keyboard.Key.Down;
            keyMap[(int)ImGuiKey.PageUp] = (int)Keyboard.Key.PageUp;
            keyMap[(int)ImGuiKey.PageDown] = (int)Keyboard.Key.PageDown;
            keyMap[(int)ImGuiKey.Home] = (int)Keyboard.Key.Home;
            keyMap[(int)ImGuiKey.End] = (int)Keyboard.Key.End;
            keyMap[(int)ImGuiKey.Insert] = (int)Keyboard.Key.Insert;
            keyMap[(int)ImGuiKey.Delete] = (int)Keyboard.Key.Delete;
            keyMap[(int)ImGuiKey.Backspace] = (int)Keyboard.Key.Backspace;
            keyMap[(int)ImGuiKey.Space] = (int)Keyboard.Key.Space;
            keyMap[(int)ImGuiKey.Enter] = (int)Keyboard.Key.Enter;
            keyMap[(int)ImGuiKey.Escape] = (int)Keyboard.Key.Escape;
            //keyMap[(int)ImGuiKey.LeftCtrl] = (int)Keyboard.Key.LeftCtrl;
            //keyMap[(int)ImGuiKey.LeftShift] = (int)Keyboard.Key.LeftShift;
            //keyMap[(int)ImGuiKey.LeftAlt] = (int)Keyboard.Key.LeftAlt;
            //keyMap[(int)ImGuiKey.LeftSuper] = (int)Keyboard.Key.LeftSuper;
            //keyMap[(int)ImGuiKey.RightCtrl] = (int)Keyboard.Key.RightCtrl;
            //keyMap[(int)ImGuiKey.RightShift] = (int)Keyboard.Key.RightShift;
            //keyMap[(int)ImGuiKey.RightAlt] = (int)Keyboard.Key.RightAlt;
            //keyMap[(int)ImGuiKey.RightSuper] = (int)Keyboard.Key.RightSuper;
            keyMap[(int)ImGuiKey.Menu] = (int)Keyboard.Key.Menu;
            keyMap[(int)ImGuiKey._0] = (int)Keyboard.Key.Number0;
            keyMap[(int)ImGuiKey._1] = (int)Keyboard.Key.Number1;
            keyMap[(int)ImGuiKey._2] = (int)Keyboard.Key.Number2;
            keyMap[(int)ImGuiKey._3] = (int)Keyboard.Key.Number3;
            keyMap[(int)ImGuiKey._4] = (int)Keyboard.Key.Number4;
            keyMap[(int)ImGuiKey._5] = (int)Keyboard.Key.Number5;
            keyMap[(int)ImGuiKey._6] = (int)Keyboard.Key.Number6;
            keyMap[(int)ImGuiKey._7] = (int)Keyboard.Key.Number7;
            keyMap[(int)ImGuiKey._8] = (int)Keyboard.Key.Number8;
            keyMap[(int)ImGuiKey._9] = (int)Keyboard.Key.Number9;
            keyMap[(int)ImGuiKey.A] = (int)Keyboard.Key.A;
            keyMap[(int)ImGuiKey.B] = (int)Keyboard.Key.B;
            keyMap[(int)ImGuiKey.C] = (int)Keyboard.Key.C;
            keyMap[(int)ImGuiKey.D] = (int)Keyboard.Key.D;
            keyMap[(int)ImGuiKey.E] = (int)Keyboard.Key.E;
            keyMap[(int)ImGuiKey.F] = (int)Keyboard.Key.F;
            keyMap[(int)ImGuiKey.G] = (int)Keyboard.Key.G;
            keyMap[(int)ImGuiKey.H] = (int)Keyboard.Key.H;
            keyMap[(int)ImGuiKey.I] = (int)Keyboard.Key.I;
            keyMap[(int)ImGuiKey.J] = (int)Keyboard.Key.J;
            keyMap[(int)ImGuiKey.K] = (int)Keyboard.Key.K;
            keyMap[(int)ImGuiKey.L] = (int)Keyboard.Key.L;
            keyMap[(int)ImGuiKey.M] = (int)Keyboard.Key.M;
            keyMap[(int)ImGuiKey.N] = (int)Keyboard.Key.N;
            keyMap[(int)ImGuiKey.O] = (int)Keyboard.Key.O;
            keyMap[(int)ImGuiKey.P] = (int)Keyboard.Key.P;
            keyMap[(int)ImGuiKey.Q] = (int)Keyboard.Key.Q;
            keyMap[(int)ImGuiKey.R] = (int)Keyboard.Key.R;
            keyMap[(int)ImGuiKey.S] = (int)Keyboard.Key.S;
            keyMap[(int)ImGuiKey.T] = (int)Keyboard.Key.T;
            keyMap[(int)ImGuiKey.U] = (int)Keyboard.Key.U;
            keyMap[(int)ImGuiKey.V] = (int)Keyboard.Key.V;
            keyMap[(int)ImGuiKey.W] = (int)Keyboard.Key.W;
            keyMap[(int)ImGuiKey.X] = (int)Keyboard.Key.X;
            keyMap[(int)ImGuiKey.Y] = (int)Keyboard.Key.Y;
            keyMap[(int)ImGuiKey.Z] = (int)Keyboard.Key.Z;
            keyMap[(int)ImGuiKey.F1] = (int)Keyboard.Key.F1;
            keyMap[(int)ImGuiKey.F2] = (int)Keyboard.Key.F2;
            keyMap[(int)ImGuiKey.F3] = (int)Keyboard.Key.F3;
            keyMap[(int)ImGuiKey.F4] = (int)Keyboard.Key.F4;
            keyMap[(int)ImGuiKey.F5] = (int)Keyboard.Key.F5;
            keyMap[(int)ImGuiKey.F6] = (int)Keyboard.Key.F6;
            keyMap[(int)ImGuiKey.F7] = (int)Keyboard.Key.F7;
            keyMap[(int)ImGuiKey.F8] = (int)Keyboard.Key.F8;
            keyMap[(int)ImGuiKey.F9] = (int)Keyboard.Key.F9;
            keyMap[(int)ImGuiKey.F10] = (int)Keyboard.Key.F10;
            keyMap[(int)ImGuiKey.F11] = (int)Keyboard.Key.F11;
            keyMap[(int)ImGuiKey.F12] = (int)Keyboard.Key.F12;
            keyMap[(int)ImGuiKey.Apostrophe] = (int)Keyboard.Key.Quote;
            keyMap[(int)ImGuiKey.Comma] = (int)Keyboard.Key.Comma;
            keyMap[(int)ImGuiKey.Minus] = (int)Keyboard.Key.Minus;
            keyMap[(int)ImGuiKey.Period] = (int)Keyboard.Key.Period;
            keyMap[(int)ImGuiKey.Slash] = (int)Keyboard.Key.Slash;
            keyMap[(int)ImGuiKey.Semicolon] = (int)Keyboard.Key.SemiColon;
            keyMap[(int)ImGuiKey.Equal] = (int)Keyboard.Key.Equals;
            keyMap[(int)ImGuiKey.LeftBracket] = (int)Keyboard.Key.LeftBracket;
            keyMap[(int)ImGuiKey.Backslash] = (int)Keyboard.Key.Backslash;
            keyMap[(int)ImGuiKey.RightBracket] = (int)Keyboard.Key.RightBracket;
            keyMap[(int)ImGuiKey.GraveAccent] = (int)Keyboard.Key.Backquote;
            keyMap[(int)ImGuiKey.CapsLock] = (int)Keyboard.Key.CapsLock;
            keyMap[(int)ImGuiKey.ScrollLock] = (int)Keyboard.Key.ScrollLock;
            keyMap[(int)ImGuiKey.NumLock] = (int)Keyboard.Key.NumLockClear;
            keyMap[(int)ImGuiKey.PrintScreen] = (int)Keyboard.Key.PrintScreen;
            keyMap[(int)ImGuiKey.Pause] = (int)Keyboard.Key.Pause;
            keyMap[(int)ImGuiKey.Keypad0] = (int)Keyboard.Key.Numpad0;
            keyMap[(int)ImGuiKey.Keypad1] = (int)Keyboard.Key.Numpad1;
            keyMap[(int)ImGuiKey.Keypad2] = (int)Keyboard.Key.Numpad2;
            keyMap[(int)ImGuiKey.Keypad3] = (int)Keyboard.Key.Numpad3;
            keyMap[(int)ImGuiKey.Keypad4] = (int)Keyboard.Key.Numpad4;
            keyMap[(int)ImGuiKey.Keypad5] = (int)Keyboard.Key.Numpad5;
            keyMap[(int)ImGuiKey.Keypad6] = (int)Keyboard.Key.Numpad6;
            keyMap[(int)ImGuiKey.Keypad7] = (int)Keyboard.Key.Numpad7;
            keyMap[(int)ImGuiKey.Keypad8] = (int)Keyboard.Key.Numpad8;
            keyMap[(int)ImGuiKey.Keypad9] = (int)Keyboard.Key.Numpad9;
            keyMap[(int)ImGuiKey.KeypadDecimal] = (int)Keyboard.Key.NumpadPeriod;
            keyMap[(int)ImGuiKey.KeypadDivide] = (int)Keyboard.Key.NumpadDivide;
            keyMap[(int)ImGuiKey.KeypadMultiply] = (int)Keyboard.Key.NumpadMultiply;
            keyMap[(int)ImGuiKey.KeypadSubtract] = (int)Keyboard.Key.NumpadMinus;
            keyMap[(int)ImGuiKey.KeypadAdd] = (int)Keyboard.Key.NumpadPlus;
            keyMap[(int)ImGuiKey.KeypadEnter] = (int)Keyboard.Key.NumpadEnter;
            keyMap[(int)ImGuiKey.KeypadEqual] = (int)Keyboard.Key.NumpadEquals;
            keyMap[(int)ImGuiKey.GamepadStart] = (int)Keyboard.Key.GamepadStart;
            keyMap[(int)ImGuiKey.GamepadBack] = (int)Keyboard.Key.GamepadBack;
            keyMap[(int)ImGuiKey.GamepadFaceUp] = (int)Keyboard.Key.GamepadY;
            keyMap[(int)ImGuiKey.GamepadFaceDown] = (int)Keyboard.Key.GamepadA;
            keyMap[(int)ImGuiKey.GamepadFaceLeft] = (int)Keyboard.Key.GamepadX;
            keyMap[(int)ImGuiKey.GamepadFaceRight] = (int)Keyboard.Key.GamepadB;
            keyMap[(int)ImGuiKey.GamepadDpadUp] = (int)Keyboard.Key.GamepadDPadUp;
            keyMap[(int)ImGuiKey.GamepadDpadDown] = (int)Keyboard.Key.GamepadDPadDown;
            keyMap[(int)ImGuiKey.GamepadDpadLeft] = (int)Keyboard.Key.GamepadDPadLeft;
            keyMap[(int)ImGuiKey.GamepadDpadRight] = (int)Keyboard.Key.GamepadDPadRight;
            keyMap[(int)ImGuiKey.GamepadL1] = (int)Keyboard.Key.GamepadLeftShoulder;
            keyMap[(int)ImGuiKey.GamepadR1] = (int)Keyboard.Key.GamepadRightShoulder;
            keyMap[(int)ImGuiKey.GamepadL2] = (int)Keyboard.Key.GamepadAxisTriggerLeftPlus;
            keyMap[(int)ImGuiKey.GamepadR2] = (int)Keyboard.Key.GamepadAxisTriggerRightPlus;
            keyMap[(int)ImGuiKey.GamepadL3] = (int)Keyboard.Key.GamepadLeftStick;
            keyMap[(int)ImGuiKey.GamepadR3] = (int)Keyboard.Key.GamepadRightStick;
            keyMap[(int)ImGuiKey.GamepadLStickUp] = (int)Keyboard.Key.GamepadAxisLeftYMinus;
            keyMap[(int)ImGuiKey.GamepadLStickDown] = (int)Keyboard.Key.GamepadAxisLeftYPlus;
            keyMap[(int)ImGuiKey.GamepadLStickLeft] = (int)Keyboard.Key.GamepadAxisLeftXMinus;
            keyMap[(int)ImGuiKey.GamepadLStickRight] = (int)Keyboard.Key.GamepadAxisLeftXPlus;
            keyMap[(int)ImGuiKey.GamepadRStickUp] = (int)Keyboard.Key.GamepadAxisRightYMinus;
            keyMap[(int)ImGuiKey.GamepadRStickDown] = (int)Keyboard.Key.GamepadAxisRightYPlus;
            keyMap[(int)ImGuiKey.GamepadRStickLeft] = (int)Keyboard.Key.GamepadAxisRightXMinus;
            keyMap[(int)ImGuiKey.GamepadRStickRight] = (int)Keyboard.Key.GamepadAxisRightXPlus;
            keyMap[(int)ImGuiKey.ModCtrl] = (int)Keyboard.Key.Control;
            keyMap[(int)ImGuiKey.ModShift] = (int)Keyboard.Key.Shift;
            keyMap[(int)ImGuiKey.ModAlt] = (int)Keyboard.Key.Alt;
            keyMap[(int)ImGuiKey.ModSuper] = (int)Keyboard.Key.GUI;
        }
    }
}
