- type: Skill
  id: StatStr
- type: Skill
  id: StatDex
- type: Skill
  id: StatCon

- type: Entity
  id: BaseObject
  abstract: true
  components:
  - type: Chip
    id: Default

- type: Entity
  id: BaseItem
  parent: BaseObject
  abstract: true
  components:
  - type: Item
  - type: Stackable

- type: Entity
  id: Dagger
  parent: BaseItem
  components:
  - type: Item
    value: 5
  - type: Chip
    id: ItemDagger

- type: Class
  id: Slime
  baseSkills:
    StatStr: 2
    StatDex: 6
    StatCon: 4

- type: Entity
  id: BaseChara
  parent: BaseObject
  abstract: true
  components:
  - type: Chara
    class: Slime
  - type: Skills

- type: Entity
  id: Putit
  parent: BaseChara
  components:
  - type: Chara
    displayName: putit
    title: The wind
    class: Slime
  - type: Chip
    id: CharaRaceSlime
