- type: Skill
  id: StatStr
- type: Skill
  id: StatDex
- type: Skill
  id: StatCon

- type: Entity
  id: BaseItem
  abstract: true
  components:
  - type: Item
  - type: Stackable

- type: Entity
  id: Dagger
  parent: BaseItem
  components:
  - type: Item
    value: 5

- type: Class
  id: Slime
  baseSkills:
    StatStr: 2
    StatDex: 6
    StatCon: 4

- type: Entity
  id: BaseChara
  abstract: true
  components:
  - type: Chara
  - type: Skills

- type: Entity
  id: Putit
  parent: BaseChara
  components:
  - type: Chara
    displayName: putit
    title: The wind
    class: Slime