- type: Entity
  id: BaseItem
  abstract: true
  components:
  - type: Item
  - type: Stackable

- type: Entity
  id: Dagger
  parent: BaseItem
  components:
  - type: Item
    value: 5


- type: Entity
  id: BaseChara
  abstract: true
  components:
  - type: Chara

- type: Entity
  id: Putit
  parent: BaseChara
  components:
  - type: Chara
    displayName: putit
    title: The wind