- type: Elona.Action
  id: Elona.DrainBlood
  hspIds:
    elona122: 601
  skillID: Elona.ActionDrainBlood
  effectID: Elona.ActionDrainBlood
  staminaCost: 7

- type: Elona.Action
  id: Elona.TouchOfWeakness
  hspIds:
    elona122: 613
  skillID: Elona.ActionTouchOfWeakness
  effectID: Elona.ActionTouchOfWeakness
  staminaCost: 10

- type: Elona.Action
  id: Elona.TouchOfHunger
  hspIds:
    elona122: 614
  skillID: Elona.ActionTouchOfHunger
  effectID: Elona.ActionTouchOfHunger
  staminaCost: 10

- type: Elona.Action
  id: Elona.TouchOfPoison
  hspIds:
    elona122: 615
  skillID: Elona.ActionTouchOfPoison
  effectID: Elona.ActionTouchOfPoison
  staminaCost: 10

- type: Elona.Action
  id: Elona.TouchOfNerve
  hspIds:
    elona122: 616
  skillID: Elona.ActionTouchOfNerve
  effectID: Elona.ActionTouchOfNerve
  staminaCost: 10

- type: Elona.Action
  id: Elona.TouchOfFear
  hspIds:
    elona122: 617
  skillID: Elona.ActionTouchOfFear
  effectID: Elona.ActionTouchOfFear
  staminaCost: 10

- type: Elona.Action
  id: Elona.TouchOfSleep
  hspIds:
    elona122: 618
  skillID: Elona.ActionTouchOfSleep
  effectID: Elona.ActionTouchOfSleep
  staminaCost: 10

- type: Elona.Action
  hspIds:
    elona122: 619
  id: Elona.DimensionalMove
  skillID: Elona.ActionDimensionalMove
  effectID: Elona.ActionDimensionalMove
  staminaCost: 15

- type: Elona.Action
  id: Elona.DrawShadow
  hspIds:
    elona122: 620
  skillID: Elona.ActionDrawShadow
  effectID: Elona.ActionDrawShadow
  staminaCost: 10

- type: Elona.Action
  id: Elona.HarvestMana
  hspIds:
    elona122: 621
#  difficulty: 700
  skillID: Elona.ActionHarvestMana
  effectID: Elona.ActionHarvestMana
  staminaCost: 10
  difficulty: 700

- type: Elona.Action
  id: Elona.BuffPunishment
  hspIds:
    elona122: 622
  skillID: Elona.ActionBuffPunishment
  effectID: Elona.ActionBuffPunishment
  staminaCost: 15
  difficulty: 500

- type: Elona.Action
  id: Elona.PrayerOfJure
  hspIds:
    elona122: 623
  skillID: Elona.ActionPrayerOfJure
  effectID: Elona.ActionPrayerOfJure
  staminaCost: 30

- type: Elona.Action
  id: Elona.AbsorbMagic
  hspIds:
    elona122: 624
  skillID: Elona.ActionAbsorbMagic
  effectID: Elona.ActionAbsorbMagic
  staminaCost: 25

- type: Elona.Action
  id: Elona.BuffLulwysTrick
  hspIds:
    elona122: 625
  skillID: Elona.ActionBuffLulwysTrick
  effectID: Elona.ActionBuffLulwysTrick
  staminaCost: 20
  difficulty: 500

- type: Elona.Action
  id: Elona.Mirror
  hspIds:
    elona122: 626
#  difficulty: 500
  skillID: Elona.ActionMirror
  effectID: Elona.ActionMirror
  staminaCost: 30
  difficulty: 500

- type: Elona.Action
  id: Elona.Change
  hspIds:
    elona122: 628
  skillID: Elona.ActionChange
  effectID: Elona.ActionChange
  staminaCost: 10

- type: Elona.Action
  id: Elona.DrawCharge
  hspIds:
    elona122: 629
  skillID: Elona.ActionDrawCharge
  effectID: Elona.ActionDrawCharge
  staminaCost: 1

- type: Elona.Action
  id: Elona.FillCharge
  hspIds:
    elona122: 630
  skillID: Elona.ActionFillCharge
  effectID: Elona.ActionFillCharge
  staminaCost: 10

- type: Elona.Action
  id: Elona.Swarm
  hspIds:
    elona122: 631
#  difficulty: 220
  skillID: Elona.ActionSwarm
  effectID: Elona.ActionSwarm
  staminaCost: 5
  difficulty: 220

- type: Elona.Action
  id: Elona.EyeOfMutation
  hspIds:
    elona122: 632
  skillID: Elona.ActionEyeOfMutation
  effectID: Elona.ActionEyeOfMutation
  staminaCost: 10

- type: Elona.Action
  id: Elona.EyeOfEther
  hspIds:
    elona122: 633
  skillID: Elona.ActionEyeOfEther
  effectID: Elona.ActionEyeOfEther
  staminaCost: 10

- type: Elona.Action
  id: Elona.EtherGround
  hspIds:
    elona122: 634
  skillID: Elona.ActionEtherGround
  effectID: Elona.ActionEtherGround
  staminaCost: 18
  difficulty: 480

- type: Elona.Action
  id: Elona.SuspiciousHand
  hspIds:
    elona122: 635
  skillID: Elona.ActionSuspiciousHand
  effectID: Elona.ActionSuspiciousHand
  staminaCost: 10

- type: Elona.Action
  id: Elona.EyeOfInsanity
  hspIds:
    elona122: 636
  skillID: Elona.ActionEyeOfInsanity
  effectID: Elona.ActionEyeOfInsanity
  staminaCost: 10

- type: Elona.Action
  id: Elona.EyeOfDimness
  hspIds:
    elona122: 638
  skillID: Elona.ActionEyeOfDimness
  effectID: Elona.ActionEyeOfDimness
  staminaCost: 10

- type: Elona.Action
  id: Elona.SuicideAttack
  hspIds:
    elona122: 644
#  difficulty: 450
  skillID: Elona.ActionSuicideAttack
  effectID: Elona.ActionSuicideAttack
  staminaCost: 20
  difficulty: 450

- type: Elona.Action
  id: Elona.Curse
  hspIds:
    elona122: 645
#  difficulty: 100
  skillID: Elona.ActionCurse
  effectID: Elona.ActionCurse
  staminaCost: 10
  difficulty: 100

- type: Elona.Action
  id: Elona.BuffDeathWord
  hspIds:
    elona122: 646
  skillID: Elona.ActionBuffDeathWord
  effectID: Elona.ActionBuffDeathWord
  staminaCost: 15
  difficulty: 500

- type: Elona.Action
  id: Elona.BuffBoost
  hspIds:
    elona122: 647
  skillID: Elona.ActionBuffBoost
  effectID: Elona.ActionBuffBoost
  staminaCost: 50
  difficulty: 500

- type: Elona.Action
  id: Elona.Insult
  hspIds:
    elona122: 648
  skillID: Elona.ActionInsult
  effectID: Elona.ActionInsult
  staminaCost: 10

- type: Elona.Action
  id: Elona.DistantAttack4
  hspIds:
    elona122: 649
  skillID: Elona.ActionDistantAttack4
  effectID: Elona.ActionDistantAttack4
  staminaCost: 10

- type: Elona.Action
  id: Elona.DistantAttack7
  hspIds:
    elona122: 650
  skillID: Elona.ActionDistantAttack7
  effectID: Elona.ActionDistantAttack7
  staminaCost: 10

- type: Elona.Action
  id: Elona.Scavenge
  hspIds:
    elona122: 651
  skillID: Elona.ActionScavenge
  effectID: Elona.ActionScavenge
  staminaCost: 10

- type: Elona.Action
  id: Elona.EyeOfMana
  hspIds:
    elona122: 652
  skillID: Elona.ActionEyeOfMana
  effectID: Elona.ActionEyeOfMana
  staminaCost: 10

- type: Elona.Action
  id: Elona.Vanish
  hspIds:
    elona122: 653
  skillID: Elona.ActionVanish
  effectID: Elona.ActionVanish
  staminaCost: 10

- type: Elona.Action
  id: Elona.Pregnant
  hspIds:
    elona122: 654
  skillID: Elona.ActionPregnant
  effectID: Elona.ActionPregnant
  staminaCost: 15

- type: Elona.Action
  id: Elona.Cheer
  hspIds:
    elona122: 656
#  difficulty: 500
  skillID: Elona.ActionCheer
  effectID: Elona.ActionCheer
  staminaCost: 28
  difficulty: 500

- type: Elona.Action
  id: Elona.Mewmewmew
  hspIds:
    elona122: 657
#  difficulty: 500
  skillID: Elona.ActionMewmewmew
  effectID: Elona.ActionMewmewmew
  staminaCost: 1
  difficulty: 500

- type: Elona.Action
  id: Elona.Decapitation
  hspIds:
    elona122: 658
  skillID: Elona.ActionDecapitation
  effectID: Elona.ActionDecapitation
  staminaCost: 10

- type: Elona.Action
  id: Elona.DropMine
  hspIds:
    elona122: 659
  skillID: Elona.ActionDropMine
  effectID: Elona.ActionDropMine
  staminaCost: 15

- type: Elona.Action
  id: Elona.ManisDisassembly
  hspIds:
    elona122: 660
  skillID: Elona.ActionManisDisassembly
  effectID: Elona.ActionManisDisassembly
  staminaCost: 10
