#
# Default
#

# NOTE: This item is used internally by the engine as the top-level config menu.
- type: Elona.ConfigMenuItem
  id: Elona.MenuDefault
  node: !type:ConfigSubmenuMenuNode
    menuSize: 370,270
    items:
      - Elona.MenuGame
      - Elona.MenuScreen
      - Elona.MenuNet
      - Elona.MenuAnime
      - Elona.MenuInput
      - Elona.MenuKeybindings
      - Elona.MenuMessage
      - Elona.MenuLanguage

#
# Game
#

- type: Elona.ConfigMenuItem
  id: Elona.MenuGame
  node: !type:ConfigSubmenuMenuNode
    #
    # Screen
    #


- type: Elona.ConfigMenuItem
  id: Elona.MenuScreen
  node: !type:ConfigSubmenuMenuNode
    items:
      - Elona.ScreenSound
      - Elona.ScreenMusic
      - Elona.ScreenMidiDevice
      - Elona.ScreenPositionalAudio
      - Elona.ScreenMuteInBackground
      - Elona.ScreenWindowMode
      - Elona.ScreenScreenResolution
      - Elona.ScreenDisplayNumber
      - Elona.ScreenUIScale
      - Elona.ScreenTileScale
      - Elona.ScreenTileFilterMode

- type: Elona.ConfigMenuItem
  id: Elona.ScreenSound
  node: !type:ConfigBoolMenuNode
    cvar: audio.sound

- type: Elona.ConfigMenuItem
  id: Elona.ScreenMusic
  node: !type:ConfigBoolMenuNode
    cvar: audio.music

- type: Elona.ConfigMenuItem
  id: Elona.ScreenMidiDevice
  node: !type:ConfigMidiDeviceMenuNode
    cvar: audio.mididevice

- type: Elona.ConfigMenuItem
  id: Elona.ScreenPositionalAudio
  node: !type:ConfigBoolMenuNode
    cvar: audio.positionalaudio

- type: Elona.ConfigMenuItem
  id: Elona.ScreenMuteInBackground
  node: !type:ConfigBoolMenuNode
    cvar: audio.muteInBackground

- type: Elona.ConfigMenuItem
  id: Elona.ScreenWindowMode
  node: !type:ConfigEnumMenuNode
    cvar: display.windowmode
    enumType: OpenNefia.Core.Graphics.WindowMode

- type: Elona.ConfigMenuItem
  id: Elona.ScreenScreenResolution
  node: !type:ConfigScreenResolutionMenuNode
    cvarWidth: display.width
    cvarHeight: display.height

- type: Elona.ConfigMenuItem
  id: Elona.ScreenDisplayNumber
  node: !type:ConfigDisplayNumberMenuNode
    cvar: display.displaynumber

- type: Elona.ConfigMenuItem
  id: Elona.ScreenUIScale
  node: !type:ConfigFloatMenuNode
    cvar: display.uiScale
    min: 1.0
    max: 4.0
    step: 0.1

- type: Elona.ConfigMenuItem
  id: Elona.ScreenTileScale
  node: !type:ConfigFloatMenuNode
    cvar: display.tileScale
    min: 1.0
    max: 4.0
    step: 0.5

- type: Elona.ConfigMenuItem
  id: Elona.ScreenTileFilterMode
  node: !type:ConfigEnumMenuNode
    cvar: display.tileFilterMode
    enumType: OpenNefia.Core.Graphics.FilterMode

#
# Net
#

- type: Elona.ConfigMenuItem
  id: Elona.MenuNet
  node: !type:ConfigSubmenuMenuNode
    #
    # Anime
    #


- type: Elona.ConfigMenuItem
  id: Elona.MenuAnime
  node: !type:ConfigSubmenuMenuNode
    items:
      - Elona.AnimeAlertWait
      - Elona.AnimeAnimationWait
      - Elona.AnimeScreenRefresh
      - Elona.AnimeBackgroundEffectWait
      - Elona.AnimeObjectMovementSpeed

- type: Elona.ConfigMenuItem
  id: Elona.AnimeAlertWait
  node: !type:ConfigFloatMenuNode
    cvar: anime.alertWait
    min: 0.0
    max: 1.0
    step: 0.1

- type: Elona.ConfigMenuItem
  id: Elona.AnimeScreenRefresh
  node: !type:ConfigIntMenuNode
    cvar: anime.screenRefresh
    min: 1
    max: 250
    step: 1

- type: Elona.ConfigMenuItem
  id: Elona.AnimeAnimationWait
  node: !type:ConfigFloatMenuNode
    cvar: anime.animationWait
    min: 0.0
    max: 10.0
    step: 0.1

- type: Elona.ConfigMenuItem
  id: Elona.AnimeBackgroundEffectWait
  node: !type:ConfigFloatMenuNode
    cvar: anime.backgroundEffectWait
    min: 0.0
    max: 1.0
    step: 0.1

- type: Elona.ConfigMenuItem
  id: Elona.AnimeObjectMovementSpeed
  node: !type:ConfigFloatMenuNode
    cvar: anime.objectMovementSpeed
    min: 0.0
    max: 5.0
    step: 0.1

#
# Input
#

- type: Elona.ConfigMenuItem
  id: Elona.MenuInput
  node: !type:ConfigSubmenuMenuNode
    #
    # Keybindings
    #


- type: Elona.ConfigMenuItem
  id: Elona.MenuKeybindings
  node: !type:ConfigSubmenuMenuNode
    #
    # Message
    #


- type: Elona.ConfigMenuItem
  id: Elona.MenuMessage
  node: !type:ConfigSubmenuMenuNode
    items:
      - Elona.MessageFade

- type: Elona.ConfigMenuItem
  id: Elona.MessageFade
  node: !type:ConfigIntMenuNode
    cvar: message.fade
    min: 0
    max: 50
    step: 10

#
# Language
#

- type: Elona.ConfigMenuItem
  id: Elona.MenuLanguage
  node: !type:ConfigSubmenuMenuNode
    items:
      - Elona.LanguageLanguage

- type: Elona.ConfigMenuItem
  id: Elona.LanguageLanguage
  node: !type:ConfigPrototypeIdsMenuNode
    cvar: language.language
    prototypeType: Language
