name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.400
    - name: Add NuGet source
      run: |
        dotnet nuget remove source nuget.org
        dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
        dotnet nuget list source
    - name: Clean
      run: dotnet clean && dotnet nuget locals all --clear
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Engine
      run: dotnet test --no-build OpenNefia.Tests/OpenNefia.Tests.csproj -v n
    - name: Test Content
      run: dotnet test --no-build OpenNefia.Content.Tests/OpenNefia.Content.Tests.csproj -v n
