name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: OpenNefia/stylua-action@1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: v0.11.3
        sha256: a20c3d177866129f701fed3693825a4050ad45c32dda5369de8365aff4dba635
        args: --check */Resources/ -g*.lua

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Engine
      run: dotnet test --no-build OpenNefia.Tests/OpenNefia.Tests.csproj -v n
    - name: Test Content
      run: dotnet test --no-build OpenNefia.Content.Tests/OpenNefia.Content.Tests.csproj -v n
