name: Publish Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Package release
      run: bash build.sh -t PackageFullRelease -- --runtime win-x64

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release/OpenNefia-win-x64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
